apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog-config
  namespace: cloud-order-system
data:
  CATALOG_DB_HOST: "catalog-db-service"
  CATALOG_DB_PORT: "5432"
  CATALOG_DB_NAME: "catalogdb"
  CATALOG_DB_USER: "cataloguser"
  CATALOG_SERVICE_HOST: "0.0.0.0"
  CATALOG_SERVICE_PORT: "5001"
  FLASK_DEBUG: "false"
